name: Build and Test (MAUI)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest  # Required for MAUI

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET 8
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore Pourfect/Pourfect.csproj

    - name: Check C# formatting (Google style)
      run: dotnet format Pourfect/Pourfect.csproj --verify-no-changes || echo "::warning::Code not formatted correctly"

    - name: Build MAUI app
      run: dotnet build Pourfect/Pourfect.csproj --configuration Release --no-restore