name: Pourfect CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore Pourfect.Tests/Pourfect.Tests.csproj

    - name: Check C# formatting
      run: dotnet format Pourfect.Tests/Pourfect.Tests.csproj --verify-no-changes || echo "::warning::Code not formatted correctly"

    - name: Build unit test project
      run: dotnet build Pourfect.Tests/Pourfect.Tests.csproj --no-restore

    - name: Run unit tests
      run: dotnet test Pourfect.Tests/Pourfect.Tests.csproj --no-build --verbosity normal